import type { Metadata } from "next";
import { Bitter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { GlobalNav } from "@/components/global-nav";

const bitter = Bitter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nerdcore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${bitter.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="relative flex min-h-screen flex-col">
            <GlobalNav />
            <main className="flex-1 pt-16">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
